name: 'Test'

on:
  workflow_dispatch:
    inputs:
      test-input:
        type: boolean
        default: false
        required: false
        description: Test input

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_INPUT: ${{ inputs.test-input || false }}
    steps:
        - uses: hmarr/debug-action@v3